### ISSUE TITLE
Jumbotron Text Hard to Read

### ISSUE THREAD

**Issue by caseywatts** [arlingtonruby/arlingtonruby.github.io#15]
I want to put this in to make the `jumbotron` more readable, but I'm not sure which file to put arlingtonruby-specific css in, if there's any right now?

```
.jumbotron p {
  font-weight: 300;
}
```

**Comment by csexton** [comment]
It was in [`app.scss`](https://github.com/arlingtonruby/arlingtonruby.github.io/blob/master/_scss/app.scss), but that seems to be deprecated with the recent changes. For now I would add it there then re-render the styles with `rake`.

We should pick either bourbon or bootstrap, and implement all the styles in one framework. Luckily we don't have much going on, so either should be pretty straight forward.

If we want to use bourbon then we get to keep scss (and the extra build step). So it is a bit of a pro-and-con :-)
